# Generated by Django 2.0.7 on 2019-04-28 14:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parkingLot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('disasterID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('disasterTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('location', models.ManyToManyField(blank=True, to='parkingLot.lot')),
            ],
        ),
    ]
