# Generated by Django 2.1.7 on 2019-04-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0017_auto_20190429_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='location',
            field=models.ManyToManyField(blank=True, to='parkingLot.Lot'),
        ),
    ]
