# Generated by Django 2.1.7 on 2019-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkrecord',
            name='location',
            field=models.CharField(default='asd', max_length=200),
        ),
    ]
