# Generated by Django 2.1.7 on 2019-04-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_parkrecord_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkrecord',
            name='checkOutTime',
            field=models.DateTimeField(blank=True, default='1970-01-01 00:00'),
        ),
        migrations.AlterField(
            model_name='parkrecord',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
