# Generated by Django 2.1.7 on 2019-04-02 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0005_parkrecord_checkouttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkrecord',
            name='checkOutTime',
        ),
    ]
