# Generated by Django 2.1.7 on 2019-04-10 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0006_remove_parkrecord_checkouttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkrecord',
            name='checkOutTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkrecord',
            name='userID',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
