# Generated by Django 2.1.7 on 2019-04-15 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticketID',
            field=models.UUIDField(default=uuid.UUID('6c837512-830b-4a24-ba42-e7bf1eb858e0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
