# Generated by Django 2.1.7 on 2019-04-24 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_auto_20190415_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='userID',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
