# Generated by Django 2.1.7 on 2019-04-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_auto_20190424_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='location',
            field=models.CharField(editable=False, max_length=30),
        ),
    ]
