# Generated by Django 2.0.7 on 2019-04-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_auto_20190424_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='userID',
            field=models.CharField(max_length=30),
        ),
    ]
