# Generated by Django 2.0.7 on 2019-04-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0013_auto_20190428_1714'),
        ('ticketing', '0013_auto_20190429_0959'),
    ]

    operations = [
    ]
