# Generated by Django 2.1.7 on 2019-04-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0014_auto_20190429_1229'),
        ('ticketing', '0014_merge_20190429_1132'),
    ]

    operations = [
    ]
