# Generated by Django 2.0.7 on 2019-04-28 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20190428_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('helpID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('questionTime', models.DateTimeField(auto_now_add=True)),
                ('answerTime', models.DateTimeField(null=True)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=300, null=True)),
                ('userID', models.ManyToManyField(blank=True, to='user.User')),
            ],
        ),
    ]
