# Generated by Django 2.0.7 on 2019-04-28 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190428_1332'),
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='userID',
        ),
        migrations.AddField(
            model_name='help',
            name='user',
            field=models.ForeignKey(default='18216001', on_delete=django.db.models.deletion.CASCADE, to='user.User'),
            preserve_default=False,
        ),
    ]
