# Generated by Django 2.0.7 on 2019-04-25 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('userID', models.CharField(max_length=30)),
                ('ticketID', models.CharField(max_length=30)),
                ('paymentTime', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
