# Generated by Django 2.0.7 on 2019-04-28 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ticketID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.Ticket'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
