# Generated by Django 2.1.7 on 2019-04-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20190428_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='duration',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
