# Generated by Django 2.0.7 on 2019-05-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_usertype'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='userID',
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default='18216001', on_delete=django.db.models.deletion.CASCADE, to='user.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingLot.Lot'),
        ),
    ]
