# Generated by Django 2.1.7 on 2019-05-14 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20190514_2157'),
        ('booking', '0004_auto_20190514_0159'),
    ]

    operations = [
    ]
