# Generated by Django 2.0.7 on 2019-04-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingLot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='status',
            field=models.CharField(default='Normal', max_length=30),
            preserve_default=False,
        ),
    ]
