# Generated by Django 2.0.7 on 2019-04-28 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parkingLot', '0002_lot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='lotName',
            field=models.CharField(default='tes', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lot',
            name='lotID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
