# Generated by Django 2.1.7 on 2019-04-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingLot', '0003_auto_20190428_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lotID',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
