# Generated by Django 2.1.7 on 2019-04-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingLot', '0005_auto_20190429_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lotID',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
