# Generated by Django 2.0.7 on 2019-04-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userMoney',
            new_name='userBalance',
        ),
    ]
